[package]
name = "hash_test"
version = "0.1.0"
authors = ["Jon Moroney <darakian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.3.3"
seahash = "4.0.1"
blake3 = "0.3.5"
